modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "cobblemon_shedders"
version = "1.4-forge-1.0.0"
displayName = "Cobblemon Shedders"
description = '''
You know how when Ninjask evolves, Shedinja pops up? That, but you can do it for arbitrary Pokemon.
'''

[[dependencies.cobblemon_shedders]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_shedders]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_shedders]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.4.0,)"
ordering = "NONE"
side = "BOTH"
